name: "Pull Request Docs Check"
on: 
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "source/"
        build-command: "sphinx-build -b html . _build"